### PR TITLE
Updating the Percona repository Keys to current

### PR DESCRIPTION
**Pull request by we-CONECT-Joe**
Solving Issue#5

https://github.com/edestecd/puppet-mariadb/issues/5

### CODE REVIEW

**Comment by edestecd** [comment]
I think the indentation is off here. Can you restore the original indentation.

I need to fix the gems for the tests. Let em do that, then you can rebase.

**Comment by edestecd** [comment]
The spec tests are again passing on master.
If you could rebase and correct the indentation, I can merge this.

**Comment by edestecd** [comment]
Did you mean to close this PR? Were you planning on opening another to fix this?

**Comment by we-CONECT-Joe** [comment]
yes! 
basically i added utility functions, have everything implemented correctly but whats missing still is a good "code formater". 
Im sure ill get around to it this weekend to get everything according to your standard. But whats to come:

**Comment by edestecd** [comment]
OK. Look forward to your PRs...

**Pull request closed without merging**
