### PR TITLE
fix(deepmerge): use renamed function

### PR DESCRIPTION
**Pull request by minorOffense**
Requires puppetlabs/mysql 9+

See https://github.com/edestecd/puppet-mariadb/issues/38

Probably needs a version bump to 3.0.0

### CODE REVIEW

**Comment by minorOffense** [comment]
Just bumping to see if the PR is acceptable or not.

**Comment by edestecd** [comment]
@minorOffense if you can rebase, this looks good to me

**Comment by minorOffense** [comment]
Updated with latest from master. Let me know if you have any questions.

**Comment by edestecd** [comment]
Do we need this any longer?

**Comment by edestecd** [comment]
Handled already in #45

**Pull request closed without merging**
